### ISSUE TITLE
Error when click on settings

### ISSUE THREAD

**Issue by ianharrigan** [Fragjacker/DoW-Mod-Manager#28]
I get this error when click on settings:

![image](https://user-images.githubusercontent.com/3024242/123072042-7bb82700-d415-11eb-833d-01ab4eeae145.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '1' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at DoW_Mod_Manager.SettingsManagerForm.InitializeGUIWithSettings(Boolean localINI, Boolean playercfgLUA)
   at DoW_Mod_Manager.SettingsManagerForm..ctor(ModManagerForm form)
   at DoW_Mod_Manager.ModManagerForm.SettingsButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DoW Mod Manager v2.1.7
    Assembly Version: 2.1.7.0
    Win32 Version: 2.1.7.0
    CodeBase: file:///D:/Steam/steamapps/common/Dawn%20of%20War%20Soulstorm/DoW%20Mod%20Manager%20v2.1.7.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Fragjacker** [comment]
Peculiar. I'll also tag @IgorTheLight since this is also relevant for him as well.

**Comment by ianharrigan** [comment]
Btw, just read a little bit of the code, and realised my Local.ini will be regened, so delete it and settings works again.

**Comment by IgorTheLight** [comment]
I would be interested in your old Local.ini so I would know what caused that problem in the first place.
Sadly to get the old one you should use file recovery utility so I'm not sure that it worth the hassle.
Anyways - I looked at all "SelectedIndex" in SettingsManagerForm.InitializeGUIWithSettings(bool localINI, bool playercfgLUA)
and couldn't spot the problem.
P. S. Glad to see another fellow programmer. I hope our code is not too terrible ;-)

**Comment by ianharrigan** [comment]
I guess logically deleted would have probably been a better term to use :) 

Heres my old Local.ini that seemed to have the issue (zipped so i can paste it) 

[__Local.zip](https://github.com/Fragjacker/DoW-Mod-Manager/files/6707294/__Local.zip)

**Comment by IgorTheLight** [comment]
Thanks!
I could reproduce the bug all the time!
Investigating...

**Comment by IgorTheLight** [comment]
I located the bug and working on solving it...
The bug is that in Local.ini "screenadapter=1" (that mean that game should select your second  videocard) while DoW Mod Manager could detect only one videocard.
So it tries to select the second videocard in the list with just one and Windows Forms tries to prevent that.
The question is: do you really have two videocards or "screenadapter=1" is just a mistake?

**Comment by IgorTheLight** [comment]
And it's fixed now!
I can't extensively test it because I don't have two videocards but it will not longer throw an exception and will actually correct the active videocard! :-)

**Comment by ianharrigan** [comment]
Nice one, i havent tested it, but im sure its working :)

Ill close this.

Cheers,
Ian

**Comment by IgorTheLight** [comment]
No-no-no!
Test it first.
It worked for me - maybe I was lucky ;-)

**Comment by ianharrigan** [comment]
OK, in meetings at the moment - is there a precompiled version?

**Comment by IgorTheLight** [comment]
Sure!
https://github.com/IgorTheLight/DoW-Mod-Manager/tree/master/DoW%20Mod%20Manager/LatestStable
Here it is - it's 2.1.8 just wothout version number in it's name
Autoupdate will be available as fast as Fragjacker could accept my last pull request (after fixing a few weird issues that GitHub will throw :-) )

**Comment by ianharrigan** [comment]
Cool - worked fine - renamed old _Local.ini back to Local.ini and verified crash on old version, no crash on new one.

👍 

Cheers,
Ian

**Comment by IgorTheLight** [comment]
Nice!
Was glad to help :-)
