### ISSUE TITLE
"Download Mod..." Causes Unhandled Exception 

### ISSUE THREAD

**Issue by ahegaosensei** [Fragjacker/DoW-Mod-Manager#40]
![image](https://github.com/Fragjacker/DoW-Mod-Manager/assets/89505632/3ce77ca4-c913-43d9-a830-65a3163a76ff)
Details are appended, not sure what's actually going on here. Happens anytime the "Download Mod..." button is clicked. Doesn't actually crash the program, since you can just Continue.
```
************** Exception Text **************
System.OverflowException: Value was either too large or too small for a character.
   at System.Convert.ToChar(Int32 value)
   at DoW_Mod_Manager.ModDownloaderForm.ReadModsFromFile(String parameter)
   at DoW_Mod_Manager.ModDownloaderForm..ctor(ModManagerForm form, String moduleFileName)
   at DoW_Mod_Manager.ModManagerForm.DownloadButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DoW Mod Manager v2.3.2.2
    Assembly Version: 2.3.2.2
    Win32 Version: 2.3.2.2
    CodeBase: file:///D:/Steam/steamapps/common/Dawn%20of%20War%20Gold/DoW%20Mod%20Manager%20v2.3.2.2.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
```

**Comment by jnowaczek** [comment]
My guess is the exception is thrown [here](https://github.com/Fragjacker/DoW-Mod-Manager/blob/276258ce684dbb1ef095852207e03f62325e7888/DoW%20Mod%20Manager/ModDownloaderForm.cs#L147) because there's an invalid character in the mod list file.

I'd suggest deleting the `DoW Mod Manager Download Mods.list` file in your game directory, it will be recreated the next time you click the "Download Mod..." button.

**Comment by ahegaosensei** [comment]
Sure thing, I'll give it a try and get back to you.

**Comment by ahegaosensei** [comment]
Nope, pitches the same error:

```
************** Exception Text **************
System.OverflowException: Value was either too large or too small for a character.
   at System.Convert.ToChar(Int32 value)
   at DoW_Mod_Manager.ModDownloaderForm.ReadModsFromFile(String parameter)
   at DoW_Mod_Manager.ModDownloaderForm..ctor(ModManagerForm form, String moduleFileName)
   at DoW_Mod_Manager.ModManagerForm.DownloadButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4645.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DoW Mod Manager v2.3.2.2
    Assembly Version: 2.3.2.2
    Win32 Version: 2.3.2.2
    CodeBase: file:///D:/Steam/steamapps/common/Dawn%20of%20War%20Gold/DoW%20Mod%20Manager%20v2.3.2.2.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

```

**Comment by jnowaczek** [comment]
Do you mind attaching your `DoW Mod Manager Download Mods.list`? I'm curious where the problem is then!

**Comment by ahegaosensei** [comment]
[DoW Mod Manager Download Mods.zip](https://github.com/Fragjacker/DoW-Mod-Manager/files/12181217/DoW.Mod.Manager.Download.Mods.zip)

Had to upload it as a zip because github won't take .LIST files but here you go

**Comment by MeneghettiRS** [comment]
I know this is somewhat old, but I'm having the same issue and found that if I delete every line after (and including) the WinterAssault [WA] tag, it shows the mods windows without errors, but empty. This could be because I'm using the Vanilla "Gold" edition and not some of the expansions. Maybe this feature works only on WA, DC or SS expansions?
